services:
  birthday-bot:
    image: birthday-bot
    container_name: birthday-bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT:?not set port in .env}:8000
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    environment:
      - TOKEN=${TOKEN:?not set telegram token in .env}
