services:
  birthday-bot:
    image: birthday-bot
    container_name: birthday-bot-debug
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./backend.debug.Dockerfile
    command: >
      sh -c "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 main.py"
    ports:
      - ${PORT:?not set port in .env}:8000
      - 5678:5678
    env_file:
      - debug.env
    volumes:
      - ./src:/app/src
    environment:
      - TOKEN=${TOKEN:?not set telegram token in .env}
