services:
  botius:
    image: botius
    container_name: telegram-bot-debug
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./backend.debug.Dockerfile
    command: >
      sh -c "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 main.py"
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./:/app 
    environment:
      - TOKEN=${TOKEN:?not set telegram token in .env}
